CREATE TABLE medicao (
  id BIGINT NOT NULL AUTO_INCREMENT,
  `timestamp` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  sensor_id BIGINT NOT NULL,
  `local` POINT SRID 4326 NOT NULL,
  noise_db DOUBLE NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB;
