name: Release (Docker Hub)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Gera timestamp e sha curto
      - name: Make timestamp+sha tag (America/Sao_Paulo)
        id: ts
        run: |
          ts=$(TZ=America/Sao_Paulo date +'%Y%m%d.%H%M%S')
          sha=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "tag=${ts}-${sha}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ vars.DOCKERHUB_REPOSITORY }}:latest
            ${{ vars.DOCKERHUB_REPOSITORY }}:${{ steps.ts.outputs.tag }}
